### PR TITLE
Use `hackport`-generated ebuilds

### PR DESCRIPTION
**Pull request by hololeap**
These are some tweaks for https://github.com/gentoo-haskell/gentoo-haskell/pull/1341:

* 32ed402beb2caa09225de982effe2f1d52456ec0 is pulled in from [your `polyparse` branch](https://github.com/Qeenon/haskell-things/tree/polyparse) so that the dependencies are together in the same branch.
* 283106d54b2f21a55a1ef736244a2eae43718087 is the `hackport`-generated ebuild for `dev-haskell/polyparse` (you got the category wrong in your commit message)
* 6b03cf0c5b0f775bfda1208c9bbd02642935c1a4 drops the old version of `dev-haskell/polyparse`
* 4984e90ea10c498d22afd8b373037628af6cf7e9 is the `hackport`-generated ebuild for `dev-haskell/cpphs`

---

If the changes look good and everything builds, you can pull this PR, then rebase the edits in your `cpphs` branch with something like:

```bash
git rebase -i --autosquash origin/master
```

This will remove the `squash!` and `fixup!` commits while moving their changes into the appropriate commit.

### CODE REVIEW

**Comment by Miezhiko** [comment]
@hololeap thank you, guess I'll check on Monday.

**Comment by hololeap** [comment]
Ok, sounds good. Please let me know if you have any suggestions to improve the workflow here. I don't have much experience with opening a PR for a PR 🙂

**Comment by Miezhiko** [comment]
well need to finish upgrading hackport =_= other than that everything looks fine at the moment

**Comment by Miezhiko** [comment]
@hololeap tested, both packages builds fine, can merge I guess. (maybe with squash)

**Pull request merged**
